EXTERNAL_CALL_IDT_GenericHandlerRedirect equ 0x0000

EXTERNAL_CALL_EXCEPTIONS_BASE equ 0x0004
EXTERNAL_CALL_Exceptions_Handler_DIVIDE_BY_ZERO                 equ EXTERNAL_CALL_EXCEPTIONS_BASE + 0x0000
EXTERNAL_CALL_Exceptions_Handler_DEBUG                          equ EXTERNAL_CALL_EXCEPTIONS_BASE + 0x0004
EXTERNAL_CALL_Exceptions_Handler_NON_MASKABLE_INTERRUPT         equ EXTERNAL_CALL_EXCEPTIONS_BASE + 0x0008
EXTERNAL_CALL_Exceptions_Handler_BREAKPOINT                     equ EXTERNAL_CALL_EXCEPTIONS_BASE + 0x000C
EXTERNAL_CALL_Exceptions_Handler_OVERFLOW                       equ EXTERNAL_CALL_EXCEPTIONS_BASE + 0x0010
EXTERNAL_CALL_Exceptions_Handler_BOUND_RANGE_EXCEEDED           equ EXTERNAL_CALL_EXCEPTIONS_BASE + 0x0014
EXTERNAL_CALL_Exceptions_Handler_INVALID_OPCODE                 equ EXTERNAL_CALL_EXCEPTIONS_BASE + 0x0018
EXTERNAL_CALL_Exceptions_Handler_DEVICE_NOT_AVAILABLE           equ EXTERNAL_CALL_EXCEPTIONS_BASE + 0x001C
EXTERNAL_CALL_Exceptions_Handler_DOUBLE_FAULT                   equ EXTERNAL_CALL_EXCEPTIONS_BASE + 0x0020
EXTERNAL_CALL_Exceptions_Handler_COPROCESSOR_SEGMENT_OVERRUN    equ EXTERNAL_CALL_EXCEPTIONS_BASE + 0x0024
EXTERNAL_CALL_Exceptions_Handler_INVALID_TSS                    equ EXTERNAL_CALL_EXCEPTIONS_BASE + 0x0028
EXTERNAL_CALL_Exceptions_Handler_SEGMENT_NOT_PRESENT            equ EXTERNAL_CALL_EXCEPTIONS_BASE + 0x002C
EXTERNAL_CALL_Exceptions_Handler_STACK_SEGMENT_FAULT            equ EXTERNAL_CALL_EXCEPTIONS_BASE + 0x0030
EXTERNAL_CALL_Exceptions_Handler_GENERAL_PROTECTION_FAULT       equ EXTERNAL_CALL_EXCEPTIONS_BASE + 0x0034
EXTERNAL_CALL_Exceptions_Handler_PAGE_FAULT                     equ EXTERNAL_CALL_EXCEPTIONS_BASE + 0x0038
EXTERNAL_CALL_Exceptions_Handler_X87_FPU_EXCPETION              equ EXTERNAL_CALL_EXCEPTIONS_BASE + 0x003C
EXTERNAL_CALL_Exceptions_Handler_ALIGNMENT_CHECK                equ EXTERNAL_CALL_EXCEPTIONS_BASE + 0x0040
EXTERNAL_CALL_Exceptions_Handler_MACHINE_CHECK                  equ EXTERNAL_CALL_EXCEPTIONS_BASE + 0x0044
EXTERNAL_CALL_Exceptions_Handler_SIMD_FPU_EXCEPTION             equ EXTERNAL_CALL_EXCEPTIONS_BASE + 0x0048
EXTERNAL_CALL_Exceptions_Handler_VIRTUALIZATION_EXCEPTION       equ EXTERNAL_CALL_EXCEPTIONS_BASE + 0x004C
EXTERNAL_CALL_Exceptions_Handler_SECURITY_EXCEPTION             equ EXTERNAL_CALL_EXCEPTIONS_BASE + 0x0050

EXTERNAL_CALL_TIMERS_BASE equ EXTERNAL_CALL_EXCEPTIONS_BASE + 0x54                      ; 0x5C
EXTERNAL_CALL_Timers_APIC_SendEOI equ EXTERNAL_CALL_TIMERS_BASE + 0x0000
EXTERNAL_CALL_Timers_APIC_Reload equ EXTERNAL_CALL_TIMERS_BASE + 0x0004
EXTERNAL_CALL_Timers_PIC_SendEOI equ EXTERNAL_CALL_TIMERS_BASE + 0x0008
EXTERNAL_CALL_Timers_PIC_Reload equ EXTERNAL_CALL_TIMERS_BASE + 0x000C

EXTERNAL_CALL_TimeSliceInterrupt equ EXTERNAL_CALL_TIMERS_BASE + 0x0010                 ; 0x6C

EXTERNAL_CALL_SYSTEM_CALL_BASE equ EXTERNAL_CALL_TimeSliceInterrupt + 0x0004            ; 0x70
EXTERNAL_CALL_MemorySystemCall equ EXTERNAL_CALL_SYSTEM_CALL_BASE + 0x0000
EXTERNAL_CALL_ProcessThreadSystemCall equ EXTERNAL_CALL_SYSTEM_CALL_BASE + 0x0004
EXTERNAL_CALL_CapabilitiesSystemCall equ EXTERNAL_CALL_SYSTEM_CALL_BASE + 0x0008
EXTERNAL_CALL_MessagingSystemCall equ EXTERNAL_CALL_SYSTEM_CALL_BASE + 0x000C
EXTERNAL_CALL_SharedMemorySystemCall equ EXTERNAL_CALL_SYSTEM_CALL_BASE + 0x0010
EXTERNAL_CALL_BiosSystemCall equ EXTERNAL_CALL_SYSTEM_CALL_BASE + 0x0014
EXTERNAL_CALL_BiosCallKernelInterrupt equ EXTERNAL_CALL_SYSTEM_CALL_BASE + 0x0018
EXTERNAL_CALL_InterruptSystemCall equ EXTERNAL_CALL_SYSTEM_CALL_BASE + 0x001C

EXTERNAL_CALL_PROCESS_THREAD_BASE equ EXTERNAL_CALL_SYSTEM_CALL_BASE + 0x0020          ; 0x8C
EXTERNAL_CALL_CreateProcess equ EXTERNAL_CALL_PROCESS_THREAD_BASE + 0x0000
EXTERNAL_CALL_MapNewOrKernelMemoryIntoProcess equ EXTERNAL_CALL_PROCESS_THREAD_BASE + 0x0004
EXTERNAL_CALL_ChangeProcessPermission equ EXTERNAL_CALL_PROCESS_THREAD_BASE + 0x0008
EXTERNAL_CALL_CreateThread equ EXTERNAL_CALL_PROCESS_THREAD_BASE + 0x000C
EXTERNAL_CALL_EnterJustProcess equ EXTERNAL_CALL_PROCESS_THREAD_BASE + 0x0010
EXTERNAL_CALL_ExitJustProcess equ EXTERNAL_CALL_PROCESS_THREAD_BASE + 0x0014
EXTERNAL_CALL_AddThreadToScheduler equ EXTERNAL_CALL_PROCESS_THREAD_BASE + 0x0018
EXTERNAL_CALL_EnterSchedulerNoReschedule equ EXTERNAL_CALL_PROCESS_THREAD_BASE + 0x001C

;Exceptions
    INTERRUPT_ID_DIVIDE_BY_ZERO                 equ 0x00
    INTERRUPT_ID_DEBUG                          equ 0x00
    INTERRUPT_ID_NON_MASKABLE_INTERRUPT         equ 0x02
    INTERRUPT_ID_BREAKPOINT                     equ 0x03
    INTERRUPT_ID_OVERFLOW                       equ 0x04
    INTERRUPT_ID_BOUND_RANGE_EXCEEDED           equ 0x05
    INTERRUPT_ID_INVALID_OPCODE                 equ 0x06
    INTERRUPT_ID_DEVICE_NOT_AVAILABLE           equ 0x07
    INTERRUPT_ID_DOUBLE_FAULT                   equ 0x08
    INTERRUPT_ID_COPROCESSOR_SEGMENT_OVERRUN    equ 0x09
    INTERRUPT_ID_INVALID_TSS                    equ 0x0A
    INTERRUPT_ID_SEGMENT_NOT_PRESENT            equ 0x0B
    INTERRUPT_ID_STACK_SEGMENT_FAULT            equ 0x0C
    INTERRUPT_ID_GENERAL_PROTECTION_FAULT       equ 0x0D
    INTERRUPT_ID_PAGE_FAULT                     equ 0x0E
    INTERRUPT_ID_X87_FPU_EXCPETION              equ 0x10
    INTERRUPT_ID_ALIGNMENT_CHECK                equ 0x11
    INTERRUPT_ID_MACHINE_CHECK                  equ 0x12
    INTERRUPT_ID_SIMD_FPU_EXCEPTION             equ 0x13
    INTERRUPT_ID_VIRTUALIZATION_EXCEPTION       equ 0x14
    INTERRUPT_ID_SECURITY_EXCEPTION             equ 0x1E

    INTERRUPT_ID_TIMER                          equ 0x20

    INTERRUPT_ID_SYSTEM_CALL_MEMORY             equ 0x40
    INTERRUPT_ID_SYSTEM_CALL_PROCESS_THREAD     equ 0x41
    INTERRUPT_ID_SYSTEM_CALL_CAPABILITIES       equ 0x42
    INTERRUPT_ID_SYSTEM_CALL_MESSAGING          equ 0x43
    INTERRUPT_ID_SYSTEM_CALL_SHARED_MEMORY      equ 0x44
    INTERRUPT_ID_SYSTEM_CALL_BIOS               equ 0x45
    INTERRUPT_ID_SYSTEM_CALL_INTERRUPT          equ 0x46
    INTERRUPT_ID_BIOS_KERNEL_CALL               equ 0x60
;Exceptions

;Paging:
    MEMORY_KENREL_MEMORY_MAX_ADDRESS        equ 0x100000
    MEMORY_KERNEL_PDE_RECURSIVE_ACCESS      equ 0x800000
    KERNEL_PDE_RECURSIVE_ACCESS equ 0x800000
    MEMORY_KERNEL_CORE_PTE_ADDRESS          equ MEMORY_KENREL_MEMORY_MAX_ADDRESS

    PAGE_SIZE equ 0x1000
    PAGING_LOW_BIT_MASK equ 0x0FFF
    PAGING_NON_CPU_BIT_MASK equ 0x0E07
    PAGING_REVERSE_NON_CPU_BIT_MASK equ 0xF1F8
    PAGING_LOW_BIT_REVERSE_MASK equ 0xF000
    FOUR_GIG_MINUS_ONE_PAGE equ 0xFFFFF000
    PAGE_SHIFT_RIGHT_BITS equ 12
    PAGING_FLAG_PRESENT equ 0x0001
    PAGING_FLAG_WRITE equ 0x0002
    PAGING_FLAG_USER equ 0x0004
    PAGING_FLAG_WRITE_SHIFT_BITS equ 1

    OS_PAGING_FLAGS_MASK equ 0x0E00
    OS_PAGING_FLAG_KERNEL equ 0x0200
    OS_PAGING_FLAG_SHARED equ 0x0400
    OS_PAGING_FLAG_GENERIC_PROTECTED equ 0x0800
    OS_PAGING_FLAG_THREAD_CONTEXT equ 0x0A00

    PROCESS_VIRTUAL_MEMORY_MAP_ADDRESS equ 0x80000000
    PROCESS_VIRTUAL_MEMORY_MAP_ENRTY_SIZE equ 0x400000
    PROCESS_VIRTUAL_MEMORY_MAP_ENRTY_SIZE_SHL_BITS equ 22
    PROCESS_PDES_RECURSIVE_ACCESS equ 0x800000 + 512 * PAGE_SIZE

    RECURSIVE_PTE_MAP_BASE equ 0xFFC00000
    RECURSIVE_PDE_MAP_BASE equ 0xFFFFF000
    OS_PROCESS_PDE_OFFSET equ 0x3FF000
;Paging

;Processes:
    PROCESS_DELETE_FLAG equ 0x00000200

    CREATE_PROCESS_FAILURE_CODE equ 0
    PID_DOESNT_EXISTS_CODE equ 0
    PID_EXISTS_CODE equ 1

    CREATE_THREAD_FAILURE_CODE equ 0
    CREATE_THREAD_SUCESS_CODE equ 1

    PROCESS_ENTER_FAILURE equ 0
    PROCESS_ENTER_SUCCESS equ 1

    THREAD_ENTER_FAILURE equ 0
    THREAD_ENTER_SUCCESS equ 1

    PROCESS_INFO_ADDRESS equ 0xFF000
    PROCESS_INFO_BASE equ 0
    PROCESS_INFO_SHARED_MEMORY_SPINLOCK equ PROCESS_INFO_BASE + 4
    PROCESS_INFO_THREAD_MANAGEMENT_SPINLOCK equ PROCESS_INFO_SHARED_MEMORY_SPINLOCK + 4
    PROCESS_INFO_SHARED_MEMORY_POINTER equ PROCESS_INFO_THREAD_MANAGEMENT_SPINLOCK + 4
    PROCESS_INFO_CAPABILITIES_SPINLOCK equ PROCESS_INFO_SHARED_MEMORY_POINTER + 4
    PROCESS_INFO_CAPABILITIES_BASE_ADDRESS equ PROCESS_INFO_CAPABILITIES_SPINLOCK + 4
    PROCESS_INFO_CAPABILITIES_N_PAGES equ PROCESS_INFO_CAPABILITIES_BASE_ADDRESS + 4
    PROCESS_INFO_MESSAGING_SPINLOCK equ PROCESS_INFO_CAPABILITIES_N_PAGES + 4
    PROCESS_INFO_MESSAGING_TABLE_BASE_ADDRESS equ PROCESS_INFO_MESSAGING_SPINLOCK + 4
    PROCESS_INFO_MESSAGING_TABLE_HANDLER_ADDRESS equ PROCESS_INFO_MESSAGING_TABLE_BASE_ADDRESS + 4

    PROCESS_INFO_PERMISSIONS_BASE equ PROCESS_INFO_MESSAGING_TABLE_HANDLER_ADDRESS + 4
    PROCESS_PERMISSION_OTHER_PROCESS_MEMORY equ 0
    PROCESS_PERMISSION_OTHER_PROCESS_THREAD equ 4
    PROCESS_PERMISSION_KERNEL_MEMORY equ 8
    PROCESS_PERMISSION_BIOS_CALL equ 12
    PROCESS_PERMISSION_PROCESS_MANAGEMENT equ 16
    PROCESS_PERMISSION_INTERRUPT_FORWARD equ 20
    PROCESS_PERMISSION_IO_PORTS equ 24
    PROCESS_PERMISSION_MAX equ 28
;Processes

;Multiprocessor
    MP_FLOATING_POINT_STRUCTURE_SEARCH_STRING equ '_MP_'
    MP_FPS_MP_FEATURES_1_OFFSET equ 11
    MP_FPS_MP_CONFIG_POINTER_OFFSET equ 4
    MP_CONFIG_TABLE_LENGTH equ 44
    MP_CONFIG_ENTRY_COUNT_OFFSET equ 34
    MP_CONFIG_LOCAL_APIC_ADDRESS_OFFSET equ 36

    INTERRUPT_COMMAND_INIT equ 0x000C4500
    INTERRUPT_COMMAND_INIT_DEASSERT equ 0x000C8500
    INTERRUPT_COMMAND_STARTUP equ 0x000C4600
    START_PROCESSOR_TRAMPOLINE_LOCATION equ 0x2000
    START_PROCESSOR_GDTR_TRAMPOLINE equ 0x2010
;Multiprocessor

;Processor
    TSS_SIZE equ 0x68
    GDT_SIZE equ 0x30
    GDT_DESCRIPTOR_SIZE equ 0x8

    PROCESSOR_CONTEXT_SIZE equ 0x400
    PROCESSOR_CONTEXT_BASE_BIT_MASK equ 0xFC00
    PROCESSOR_CONTEXT_TSS_OFFSET equ PROCESSOR_CONTEXT_SIZE - TSS_SIZE
    PROCESSOR_CONTEXT_GDT_OFFSET equ PROCESSOR_CONTEXT_TSS_OFFSET - GDT_SIZE
    PROCESSOR_CONTEXT_GDT_DESCRIPTOR_OFFSET equ PROCESSOR_CONTEXT_GDT_OFFSET - GDT_DESCRIPTOR_SIZE
    PROCESSOR_CONTEXT_IN_INTERRUPT equ PROCESSOR_CONTEXT_GDT_DESCRIPTOR_OFFSET - 4
    PROCESSOR_CONTEXT_INTS_PROCESSED equ PROCESSOR_CONTEXT_IN_INTERRUPT - 4
    PROCESSOR_CONTEXT_IN_PROCESS_RETURN_MODE equ PROCESSOR_CONTEXT_INTS_PROCESSED - 4
    PROCESSOR_CONTEXT_THREAD_TIME equ PROCESSOR_CONTEXT_IN_PROCESS_RETURN_MODE - 4
    PROCESSOR_CONTEXT_CURRENT_THREAD_PAGED_ADDRESS equ PROCESSOR_CONTEXT_THREAD_TIME - 4
    PROCESSOR_CONTEXT_CURRENT_PROCESS equ PROCESSOR_CONTEXT_CURRENT_THREAD_PAGED_ADDRESS - 4
    PROCESSOR_CONTEXT_EXECUTION_STATE equ PROCESSOR_CONTEXT_CURRENT_PROCESS- 4
        PROCESSOR_EXECUTION_STATE_HALTED equ 0
        PROCESSOR_EXECUTION_STATE_EXECUTING equ 1
        PROCESSOR_EXECUTION_STATE_INTERRUPT equ 2
    PROCESSOR_CONTEXT_STACK_BASE equ PROCESSOR_CONTEXT_EXECUTION_STATE - 4

    LOCAL_APIC_ID_REGISTER_OFFSET equ 0x20
    LOCAL_APIC_TPR_REGISTER equ 0x80
    LOCAL_APIC_EOI_REGISTER equ 0xB0
    LOCAL_APIC_SPURIOUS_INTERRUPT_REGISTER_OFFSET equ 0xF0
    LOCAL_APIC_INTERRUPT_COMMAND_REGISTER_LOWER_OFFSET equ 0x300
    LOCAL_APIC_INTERRUPT_COMMAND_REGISTER_UPPER_OFFSET equ 0x310
    LOCAL_APIC_INTERRUPT_LVT_TIMER_REGISTER equ 0x320
    LOCAL_APIC_INTERRUPT_TIMER_INTIAL_COUNT equ 0x380
    LOCAL_APIC_INTERRUPT_TIMER_CURRENT_COUNT equ 0x390
    LOCAL_APIC_INTERRUPT_TIMER_DIVIDER_REGISTER equ 0x3E0
    LOCAL_APIC_LVT_LINT0 equ 0x350
    LOCAL_APIC_LVT_LINT1 equ 0x360
    LOCAL_APIC_ESR_REGISTER equ 0x280
    LOCAL_APIC_LDR_REGISTER equ 0xE0
    LOCAL_APIC_DFR_REGISTER equ 0xE0
;Processor

;Threads
    THREAD_STACK_SAVE_SIZE equ 12 * 4
    THREAD_STACK_CODE_SEG_LOCATION equ 8 * 4
    THREAD_STACK_EIP_LOCATION equ 7 * 4

    EFLAGS_INTERRUPT_ENABLE_MASK equ 0x0200

    THREAD_SPINLOCK equ 0
    THREAD_REFERENCES equ THREAD_SPINLOCK + 4
    THREAD_OWNER_PROCESS equ THREAD_REFERENCES + 4
    THREAD_CURRENT_PROCESS equ THREAD_OWNER_PROCESS + 4
    THREAD_EXECUTION_STATE equ THREAD_CURRENT_PROCESS + 4
        THREAD_EXECUTION_STATE_MASK_SCHEDULED equ 0x1
        THREAD_EXECUTION_STATE_MASK_EXECUTING equ 0x2
        THREAD_EXECUTION_STATE_MASK_HALT_REQUESTED equ 0x4
        THREAD_EXECUTION_STATE_MASK_DESTROY equ 0x8
        THREAD_EXECUTION_STATE_MASK_RESCHEDULE_REQUESTED equ 0x10

        THREAD_EXECUTION_STATE_BYTE_REVERSE_MASK_SCHEDULED equ 0xFE
        THREAD_EXECUTION_STATE_BYTE_REVERSE_MASK_EXECUTING equ 0xFD
        THREAD_EXECUTION_STATE_BYTE_REVERSE_MASK_HALT_REQUESTED equ 0xFB
        THREAD_EXECUTION_STATE_BYTE_REVERSE_MASK_DESTROY equ 0xF7
        THREAD_EXECUTION_STATE_BYTE_REVERSE_MASK_RESCHEDULE_REQUESTED equ 0xEF

    THREAD_MESSAGE_STACK_POINTER equ THREAD_EXECUTION_STATE + 4
        THREAD_MESSAGE_STACK_BASE equ 2048
        THREAD_MESSAGE_STACK_MAX_SIZE equ 2048

    THREAD_INTERRUPT_STACK_SAVE equ THREAD_MESSAGE_STACK_POINTER + 4
    THREAD_PDE_ADDRESS_SAVE equ THREAD_INTERRUPT_STACK_SAVE + THREAD_STACK_SAVE_SIZE
    THREAD_INTERRUPT_FP_SAVE equ THREAD_PDE_ADDRESS_SAVE + 4
    THREAD_INTERRUPT_FP_SAVE_SIZE equ 108

    CHANGE_THREAD_EXECUTION_SCHEDULE equ 1
    CHANGE_THREAD_EXECUTION_HALT equ 2
;Threads

;Memory
    USER_MEMORY_LOWER_LIMIT equ MEMORY_KENREL_MEMORY_MAX_ADDRESS
    USER_MEMORY_UPPER_LIMIT equ RECURSIVE_PTE_MAP_BASE

    MEMORY_CHECK_SUCESS_CODE equ 1
    MEMORY_CHECK_FAILURE_CODE equ 0

    MEMORY_SYSTEM_CALL_SUCCESS equ 1
    MEMORY_SYSTEM_CALL_FAILURE equ 0

    MEMORY_SYSTEM_CALL_NEW_MEMORY equ 0
    MEMORY_SYSTEM_CALL_MOVE_MEMORY equ 1
    MEMORY_SYSTEM_CALL_SHARE_MEMORY equ 2
    MEMORY_SYSTEM_CALL_KERNEL_MEMORY equ 3
;Memory

;Shared Memory
    SHARED_MEMORY_FAIL equ 0
    SHARED_MEMORY_SUCCESS equ 1

    MAX_SHARED_MEMORY_SEGMENTS equ 1024

    MEMORY_SEGMENT_MARKER_ACCESS_ALLOWED equ 1
    MEMORY_SEGMENT_MARKER_WRITE_ALLOWED equ PAGING_FLAG_WRITE

    SHARED_MEMORY_MODIFY_ADD_SEGMENT equ 1
    SHARED_MEMORY_MODIFY_REMOVE_SEGMENT equ 2
    SHARED_MEMORY_MODIFY_CHANGE_PERMISSIONS equ 3
    SHARED_MEMORY_MODIFY_REMOVE_SEGMENT_NO_SPINLOCK equ 0x10002

    DELETE_SHARED_MEMORY_SEGMENT equ 0
    DELETE_SHARED_MEMORY_SEGMENT_NO_SPINLOCK equ 0x10000
;Shared Memory

;Scheduler
    SCHEDULER_EMPTY_CODE equ 0xFFFFFFFF
    SCHEDULER_ENTRY_REMOVED_CODE equ 0xFFFFFFFE
;Scheduler

;Messaging
    MESSAGE_STACK_ENTRY_SIZE equ 24
    MESSAGING_REGION_N_PAGES equ 1024
    MESSAGING_N_SLOTS equ 512
;Messaging

;Real Mode
    REAL_MODE_GDT equ 0x3000 - 0x18

    REAL_MODE_GDT_DESCRIPTOR        equ REAL_MODE_GDT - 0x0008
    REAL_MODE_IDT_DESCRIPTOR        equ REAL_MODE_GDT - 0x0010

    BIOS_CALL_SAVE_CR0              equ REAL_MODE_GDT - 0x0014
    BIOS_CALL_SAVE_DS               equ REAL_MODE_GDT - 0x0018
    BIOS_CALL_SAVE_ES               equ REAL_MODE_GDT - 0x001C
    BIOS_CALL_SAVE_GS               equ REAL_MODE_GDT - 0x0020
    BIOS_CALL_SAVE_FS               equ REAL_MODE_GDT - 0x0024

    BIOS_CALL_VARIABLE_STACK_SIZE equ 0x28
    BIOS_CALL_VARIABLE_STACK_BASE   equ REAL_MODE_GDT - 0x0024 - BIOS_CALL_VARIABLE_STACK_SIZE 
        BIOS_CALL_EFLAGS                equ BIOS_CALL_VARIABLE_STACK_BASE + 0x0024
        BIOS_CALL_EAX                   equ BIOS_CALL_VARIABLE_STACK_BASE + 0x0020
        BIOS_CALL_ECX                   equ BIOS_CALL_VARIABLE_STACK_BASE + 0x001C
        BIOS_CALL_EDX                   equ BIOS_CALL_VARIABLE_STACK_BASE + 0x0018
        BIOS_CALL_EBX                   equ BIOS_CALL_VARIABLE_STACK_BASE + 0x0014
        BIOS_CALL_ESP_UNUSED            equ BIOS_CALL_VARIABLE_STACK_BASE + 0x0010
        BIOS_CALL_EBP                   equ BIOS_CALL_VARIABLE_STACK_BASE + 0x000C
        BIOS_CALL_ESI                   equ BIOS_CALL_VARIABLE_STACK_BASE + 0x0008
        BIOS_CALL_EDI                   equ BIOS_CALL_VARIABLE_STACK_BASE + 0x0004
        BIOS_CALL_INTERRUPT             equ BIOS_CALL_VARIABLE_STACK_BASE + 0x0000

    BIOS_CALL_REAL_MODE_STACK equ BIOS_CALL_VARIABLE_STACK_BASE
;Real Mode

KERNEL_DATA_AREA_BASE_ADDRESS   equ 0x60000
KERNEL_DATA_AREA_LENGTH         equ 0x20000

    PROCESSOR_CONTEXTS_MAX_ADDRESS equ 0x70000

    IDT_BASE_ADDRESS equ 0x70000
    IDT_DESCRIPTOR_ADDRESS equ IDT_BASE_ADDRESS + 0x0800

    GLOBAL_OS_VARIABLES_BASE equ IDT_DESCRIPTOR_ADDRESS + 0x0008

        PROCESSOR_VARS equ GLOBAL_OS_VARIABLES_BASE + 0x0000
            MULTIPROCESSOR_TYPE equ PROCESSOR_VARS + 0
                MULTIPROCESSOR_TYPE_NO_SMP equ 0
                MULTIPROCESSOR_TYPE_SMP equ 1
            POINTER_TO_MP_CONFIG_TABLE_ADDRESS equ PROCESSOR_VARS + 4
            POINTER_TO_PROCESSOR_INFO_BASE_ADDRESS equ PROCESSOR_VARS + 8
            POINTER_TO_NUMBER_OF_PROCESSORS equ PROCESSOR_VARS + 16
            POINTER_TO_IO_APIC_TABLE_BASE equ PROCESSOR_VARS + 20
            POINTER_TO_LOCAL_APIC_ADDRESS equ PROCESSOR_VARS + 24
            MULTIPROCESSOR_INITIALIZATION_DONE equ PROCESSOR_VARS + 28

        MEMORY_TABLE_VARS_BASE equ GLOBAL_OS_VARIABLES_BASE + 0x0040
            MEMORY_TABLE_POINTER_TO_ENQUEUE equ MEMORY_TABLE_VARS_BASE + 0
            MEMORY_TABLE_POINTER_TO_DEQUEUE equ MEMORY_TABLE_VARS_BASE + 4
            MEMORY_TABLE_POINTER_TO_START_ADDRESS equ MEMORY_TABLE_VARS_BASE + 8
            MEMORY_TABLE_POINTER_TO_END_ADDRESS equ MEMORY_TABLE_VARS_BASE + 16
            MEMORY_TABLE_SPINLOCK equ MEMORY_TABLE_VARS_BASE + 20
            ZERO_PAGE_SPINLOCK equ MEMORY_TABLE_VARS_BASE + 24
            MULTIPLE_PROCESS_MEMORY_SPINLOCK_ACCESS equ MEMORY_TABLE_VARS_BASE + 28
        
        TIMER_VARIABLES_BASE equ GLOBAL_OS_VARIABLES_BASE + 0x0060
            TIMER_POINTER_TO_TYPE equ TIMER_VARIABLES_BASE + 0
                TIMER_TYPE_PIC_TIMER equ 1
                TIMER_TYPE_APIC_TIMER equ 2
            TIMER_POINTER_TO_RELOAD_TIME equ TIMER_VARIABLES_BASE + 4
            TIMER_POINTER_TO_EOI_FUNCTION equ TIMER_VARIABLES_BASE + 8
            TIMER_POINTER_TO_RELOAD_FUNCTION equ TIMER_VARIABLES_BASE + 12

        BIOS_CALL_VARIABLES equ GLOBAL_OS_VARIABLES_BASE + 0x0080
            BIOS_CALL_SPINLOCK equ BIOS_CALL_VARIABLES
            BIOS_CALL_PROCESSOR_LOCAL_APIC_ID equ BIOS_CALL_VARIABLES + 4
            BIOS_CALL_CALLING_PROCESS equ BIOS_CALL_VARIABLES + 8
            BIOS_CALL_STACK_VARIABLE_LOCATION equ BIOS_CALL_VARIABLES + 12
            BIOS_CALL_OPERATION_STATUS equ BIOS_CALL_VARIABLES + 16
            BIOS_CALL_SUCCESS equ BIOS_CALL_VARIABLES + 20

        SCHEDULER_VARIABLE_BASE equ GLOBAL_OS_VARIABLES_BASE + 0x00A0
            SCHEDULER_TABLE_ENQUEUE equ SCHEDULER_VARIABLE_BASE + 0
            SCHEDULER_TABLE_DEQUEUE equ SCHEDULER_VARIABLE_BASE + 4
            INTERRUPT_SCHEDULER_TABLE_ENQUEUE equ SCHEDULER_VARIABLE_BASE + 8
            INTERRUPT_SCHEDULER_TABLE_DEQUEUE equ SCHEDULER_VARIABLE_BASE + 12
            SCHEDULER_TABLE_SPINLOCK equ SCHEDULER_VARIABLE_BASE + 16
            INTERRUPT_SCHEDULER_TABLE_ENQUEUE_SPINLOCK equ SCHEDULER_VARIABLE_BASE + 20
            INTERRUPT_SCHEDULER_TABLE_DEQUEUE_SPINLOCK equ SCHEDULER_VARIABLE_BASE + 24

    KERNEL_PDE_ADDRESS equ 0x71000

    PROCESS_TABLE_ADDRESS equ KERNEL_PDE_ADDRESS + 0x800                    ; 0x71800
    PROCESS_SPINLOCK_TABLE_ADDRESS equ PROCESS_TABLE_ADDRESS + 0x800        ; 0x72000
    PROCESS_PID_TABLE_ADDRESS equ PROCESS_SPINLOCK_TABLE_ADDRESS + 0x800    ; 0x72800
    PROCESS_TABLES_END_ADDRESS equ PROCESS_PID_TABLE_ADDRESS + 0x800        ; 0x73000

    SCHEDULER_TABLE_BASE_ADDRESS equ PROCESS_TABLES_END_ADDRESS             ; 0x73000
    SCHEDULER_TABLES_END_ADDRESS equ SCHEDULER_TABLE_BASE_ADDRESS + 0x1000  ; 0x74000
    INTERRUPT_SCHEDULER_TABLE_BASE_ADDRESS equ SCHEDULER_TABLES_END_ADDRESS
    INTERRUPT_SCHEDULER_TABLE_END_ADDRESS equ INTERRUPT_SCHEDULER_TABLE_BASE_ADDRESS + 0x1000

    IDT_GENERIC_HANDLER_REDIRECT_TABLE equ INTERRUPT_SCHEDULER_TABLE_END_ADDRESS     ; 0x75000
    PROCESS_INTERRUPT_HANDLERS_TABLE equ IDT_GENERIC_HANDLER_REDIRECT_TABLE + 0x800

    LOCAL_APIC_PAGED_LOCATION equ 0x77000
    MULTIPROCESSOR_LOCAL_APIC_ID_TABLE equ 0x78000
    MULTIPROCESSOR_IO_APIC_TABLE equ 0x78400